# Site
name: 'Sheroz Samatov'
description: "Thanks for stopping by! I am a beginner programmer, welcome to my blog. This description will be updated again. I will write about various subjects until I find a good niche subject to focus on. 

At the moment I am learning Jekyll, Liquid, YAML and Shopify in order to start freelancing. I am into programming, cryptocurrency and finances, so there will probably be posts related to these topics. 

The main goal is to expose myself to the programming community and learn as I go."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
url: 'sherozsamatov.github.io'
disqus: ''
email: 'sherozonline@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:categories/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sheroz:
      name:           Sheroz
      site:           https://www.sherozsamatov.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "I created this blog to force myself to learn Jekyll :-D!"
      email:          sherozsamatov@gmail.com
      twitter:        https://twitter.com/sherozsamatov

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sheroz
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]