# Site
name: 'Sheroz Samatov'
description: "Welcome to my personal blog! Here I will do my best to document my journey as a beginner front-end developer, share my insights and experiences, lessons I've learnt or mistakes I made in order to help someone who might be taking the same path as me. I will write about the solutions to problems I encountered while learning and growing, create tutorials and anything that might be of value to newbie developers. At the moment I am learning Jekyll, Liquid, YAML and Shopify in order to start my freelancing career. Be sure to check out my articles about these technologies as well as how to get started as a freelancer and follow me on social media."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: ''
disqus: ''
email: 'sherozonline@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:categories/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sheroz:
      name:           Sheroz
      site:           https://www.sherozsamatov.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Sheroz, the owner of this blog. I am passionate about writing and programming. I hope you find my articles useful!"
      email:          sherozsamatov@gmail.com
      twitter:        https://twitter.com/sherozsamatov

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sheroz
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]